import { StringMatchConfig } from "./types";

export const STAPLES: StringMatchConfig[] = [
  { match: "salt" },
  {
    match: "pepper",
    excludeIf: [
      "bell",
      "jalapeno",
      "serrano",
      "habanero",
      "poblano",
      "banana",
      "chili",
      "chilli",
      "red",
      "green",
      "yellow",
      "orange",
      "roasted",
      "sweet",
    ],
    keepIf: ["powder", "flakes", "ground", "cayenne"],
  },
  { match: "olive oil" },
  { match: "vegetable oil" },
  { match: "canola oil" },
  { match: "cooking spray" },
  { match: "sugar" },
  { match: "flour" },
  { match: "baking powder" },
  { match: "baking soda" },
  { match: "vanilla extract" },
  { match: "cornstarch" },
  { match: "yeast" },
  { match: "paprika" },
  { match: "cumin" },
  { match: "garlic powder" },
  { match: "onion powder" },
  { match: "oregano" },
  { match: "thyme" },
  { match: "rosemary" },
  { match: "cayenne" },
  { match: "chili powder" },
  { match: "cinnamon" },
  { match: "nutmeg" },
  { match: "ginger powder" },
  { match: "ground ginger" },
  { match: "turmeric" },
  { match: "coriander" },
  { match: "cardamom" },
  { match: "cloves powder" },
  { match: "allspice" },
  { match: "mustard powder" },
  { match: "parsley" },
  { match: "basil" },
  {
    match: "sage",
    excludeIf: ["sausage"],
  },
  {
    match: "lemon juice",
    excludeIf: ["fresh", "squeezed"],
  },
  {
    match: "lime juice",
    excludeIf: ["fresh", "squeezed"],
  },
  { match: "water" },
];

export const VOLUME_UNITS: string[] = [
  "cup",
  "cups",
  "tablespoon",
  "tablespoons",
  "tbsp",
  "teaspoon",
  "teaspoons",
  "tsp",
  "ounce",
  "ounces",
  "oz",
  "ml",
];

export const OTHER_UNITS: string[] = [
  "pound",
  "pounds",
  "lb",
  "lbs",
  "clove",
  "cloves",
  "can",
  "cans",
  "gram",
  "grams",
  "g",
  "small",
  "large",
  "medium",
  "head",
  "heads",
  "bulb",
  "bulbs",
];

export const TO_TEASPOONS: Record<string, number> = {
  teaspoon: 1,
  tsp: 1,
  tablespoon: 3,
  tbsp: 3,
  ounce: 6,
  oz: 6,
  cup: 48,
  ml: 0.202884,
};

export const PREP_KEYWORDS: string[] = [
  "minced",
  "diced",
  "chopped",
  "sliced",
  "grated",
  "crushed",
  "shredded",
  "toasted",
  "melted",
  "softened",
  "beaten",
  "mashed",
  "julienned",
  "drained",
  "wedge",
  "wedges",
  "divided",
  "grate",
  "thinly",
  "finely",
  "coarsely",
  "room temperature",
  "finely crushed",
];

export const SKIP_TERMS: string[] = [
  "pasta water",
  "cooking water",
  "reserved water",
];
